### PR TITLE
Make temp directory creation more robust, log only on errors

### PR DESCRIPTION
**Pull request by augustozanellato**

### CODE REVIEW

**Comment by augustozanellato** [comment]
> Seems like it didn't actually improve anything? The error msg may be clearer, but seems like the same error would have been caught too?

Yeah, effectively my commit msg isn't accurate, it's not more robust, it just gives clearer error msgs and it prevents false errors (e.g. in all runs after the first one `could not create directory` is printed even if there wasn't any need to try and create it in the first place)

**Comment by ickc** [comment]
a few of those behaviors are opinionated and I don't think changing them are necessary. Eg emitting stderr or not when success; and the check on existing dir. For the later one, technically it can still fails as between the first check and 2nd check something else can happen on the file system. So rather than trying to be slightly more helpful and points out to the user how it fails, it may be better simply to let it fails and let the user figure it out (eg we aren't providing all different reasons why it may fail here)

It does has a change in behavior, that you now allows the directory to be existed on the first place. IIRC @jerri made the original code. Do you want to comment on why you don't allow that dir to be existed?

Even if we want to change that behavior, `so.makedirs` with the exist ok option is a better fit.

**Comment by ickc** [comment]
What happened? @augustozanellato, do you have control over @sevenelevendevunipd?

**Comment by augustozanellato** [comment]
> What happened? @augustozanellato, do you have control over @sevenelevendevunipd?

Yeah, it's a organization I'm using with some friends for an university project.
I deleted the fork (without thinking about the consequences on the PR :P) because we switched to panflute because it had cleaner APIs and supported out of the box document metadata editing.
I'm still happy about merging my changes here tho, so I'll make another PR from my personal account.

> It does has a change in behavior, that you now allows the directory to be existed on the first place.

IMO it should allow for that because otherwise you'll get something that looks like an error logged to stdout on every document build after the first one.

**Comment by ickc** [comment]
I'm a co-maintainer in panflute, both maintainers in pandocfilters endorse panflute and IMO you should write new filters using that.

About the point of allowing existing temp dir, it depends. That's why I asked the original contributor of that code. I'd think more about it later.

About stderr, printing to stderr is safe. It acts more like logging in this case. (Of course one should use a proper logger rather than that, but it's only that way for historical reasons. This may change but I'm not sure how much change I'm going to make here.)

**Comment by augustozanellato** [comment]
> About stderr, printing to stderr is safe. It acts more like logging in this case. (Of course one should use a proper logger rather than that, but it's only that way for historical reasons. This may change but I'm not sure how much change I'm going to make here.)
Yep, my point wasn’t about printing to stderr, the problem is that the “error” message is worded like an error when in fact it’s a likely and normal behavior.
“Could not create directory” sounds like something went wrong while creating the output directory imho.

**Pull request closed without merging**
