### PR TITLE
add git-diff codeblock

### PR DESCRIPTION
**Pull request by silvio**
Signed-off-by: Silvio Fricke silvio.fricke@gmail.com

### CODE REVIEW

**Comment by silvio** [comment]
It would be good to review my code, I don't have programmed in python since ages.

**Comment by silvio** [comment]
@jgm I had updated the patchset. The sample is working. You think its usefull to include it in the *pandocfilters* repository?

**Comment by silvio** [comment]
@jgm not interested? so I will kill this pull request.

**Comment by jgm** [comment]
@silvio don't kill it.  I just haven't had time to look at it.

**Comment by silvio** [comment]
Aye aye, Sir!

**Pull request closed without merging**
